import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Write rules to disk in the specified format.
 * 
 * Formats:
 * - cursor: .cursor/rules/*.mdc files (one per rule)
 * - claude-md: Single CLAUDE.md file
 * - agents-md: Single AGENTS.md file  
 * - copilot: Single .github/copilot-instructions.md file
 * - windsurf: Single .windsurfrules file
 */

function toMarkdownSection(rule) {
  // Strip frontmatter, keep body
  const body = rule.content.replace(/^---[\s\S]*?---\n\n?/, '');
  return body;
}

function toCombinedMarkdown(rules, header) {
  let output = `${header}\n\n`;
  output += `<!-- Generated by rule-gen using Google Gemini -->\n\n`;
  for (const rule of rules) {
    output += toMarkdownSection(rule);
    output += '\n---\n\n';
  }
  return output.trim() + '\n';
}

export const writer = {
  async write(rules, projectPath, format) {
    const written = [];

    switch (format) {
      case 'cursor': {
        const rulesDir = join(projectPath, '.cursor', 'rules');
        await mkdir(rulesDir, { recursive: true });
        for (const rule of rules) {
          const filePath = join(rulesDir, `${rule.filename}.mdc`);
          await writeFile(filePath, rule.content, 'utf-8');
          written.push(`.cursor/rules/${rule.filename}.mdc`);
        }
        break;
      }

      case 'claude-md': {
        const content = toCombinedMarkdown(rules, '# CLAUDE.md');
        const filePath = join(projectPath, 'CLAUDE.md');
        await writeFile(filePath, content, 'utf-8');
        written.push('CLAUDE.md');
        break;
      }

      case 'agents-md': {
        const content = toCombinedMarkdown(rules, '# AGENTS.md');
        const filePath = join(projectPath, 'AGENTS.md');
        await writeFile(filePath, content, 'utf-8');
        written.push('AGENTS.md');
        break;
      }

      case 'copilot': {
        const dir = join(projectPath, '.github');
        await mkdir(dir, { recursive: true });
        const content = toCombinedMarkdown(rules, '# Copilot Instructions');
        const filePath = join(dir, 'copilot-instructions.md');
        await writeFile(filePath, content, 'utf-8');
        written.push('.github/copilot-instructions.md');
        break;
      }

      case 'windsurf': {
        const content = toCombinedMarkdown(rules, '# Windsurf Rules');
        const filePath = join(projectPath, '.windsurfrules');
        await writeFile(filePath, content, 'utf-8');
        written.push('.windsurfrules');
        break;
      }

      default:
        throw new Error(`Unknown format: ${format}. Use: cursor, claude-md, agents-md, copilot, windsurf`);
    }

    return written;
  },
};
